config/routes.rb
Rails.application.routes.draw do      
  root "application#hello"
  require "sidekiq/web"
  require "sidekiq/cron/web"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    registrations: "registrations",
    invitations: "admin/invitations"
  }

  namespace :admin do
    resources :users do 
      post '/archive', to: "users#archive"
    end
  end

  get "account/:id", to: "application#select_tenant", as: :select_tenant
  resources :boards, path: :canvasses
  resources :cards do 
    member do 
      patch :move
    end
  end
  resources :forms, path: :questions do 
    post '/pause', to: "forms#pause"
    resources :fields do 
      resources :field_values
    end
  end
  resources :lists do 
    member do 
      get :cancel
    end
    resources :cards, module: :lists
  end
  resources :templates
  resources :work_items, except: [:show, :destroy, :edit] do 
    patch "/cancel", to: "work_items#cancel"
  end
  get '/user_account', to: 'user_accounts#show'
end

app/views/templates/_form.html.haml
= turbo_frame_tag dom_id_for_records(@template) do
  .col-md-6
    = simple_form_for(@template, data: { "turbo-frame" => "_top" }) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .form-inputs.mb-3
        = f.input :title
        = f.input :description
      .form-actions
        = f.button :submit, class: "btn btn-sm btn-outline-secondary float-end"

app/views/templates/edit.html.haml
%h1 Editing Template
= render 'form', template: @template
= link_to 'Show', @template
|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
%h1 Templates
%table
  %thead
    %tr
      %th Title
      %th Description
      %th{colspan: "3"}
  %tbody
    - @templates.each do |template|
      %tr
        %td= template.title
        %td= template.description
        %td= link_to 'Show', template
        %td= link_to 'Edit', edit_template_path(template)
        %td= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Template', new_template_path

app/views/templates/new.html.haml
%h1 New Template
= render 'form', template: @template
= link_to 'Back', templates_path

app/views/templates/show.html.haml
%h1 Template
%p
  %strong Title:
  = @template.title
%p
  %strong Template lists:
  - @template.template_lists.each do |template_list|
    %p= template_list.title
= link_to 'Edit', edit_template_path(@template)
|
= link_to 'Back', templates_path