config/routes.rb
Rails.application.routes.draw do      
  root "application#hello"
  require "sidekiq/web"
  require "sidekiq/cron/web"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    registrations: "registrations",
    invitations: "admin/invitations"
  }

  namespace :admin do
    resources :users do 
      post '/archive', to: "users#archive"
    end
  end

  get "account/:id", to: "application#select_tenant", as: :select_tenant
  resources :boards, path: :canvasses
  resources :cards do 
    member do 
      patch :move
    end
  end
  resources :forms, path: :questions do 
    post '/pause', to: "forms#pause"
    resources :fields do 
      resources :field_values
    end
  end
  resources :lists do 
    member do 
      get :cancel
    end
    resources :cards, module: :lists
  end
  resources :templates
  resources :work_items, except: [:show, :destroy, :edit] do 
    patch "/cancel", to: "work_items#cancel"
  end
  get '/user_account', to: 'user_accounts#show'
end

app/models/card.rb
class Card < ApplicationRecord
  include ActionView::RecordIdentifier
  
  acts_as_tenant(:account)
  belongs_to :list
  acts_as_list scope: :list
  belongs_to :account
  has_one :created_action, -> { where(action_type: 1, action_object_type: "Card") }, class_name: "Action", foreign_key: :action_object_id, dependent: :destroy
  has_one :creator, through: :created_action, source: :actor
  validates :title, presence: true

  default_scope { order(position: :asc) }

  after_create_commit do
    broadcast_append_to [list, :cards], target: "#{dom_id(list)}_cards"
  end

  after_update_commit do
    broadcast_replace_to self 
    board = self.list.board
    broadcast_replace_to(board, partial: "lists/index", locals: { board: board }, target: dom_id(board))
  end

  after_destroy_commit do
    broadcast_remove_to self
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.turbo_stream {}
      format.html { redirect_to @card.list.board }
    end
  end

  def move
    @card.list_id = params[:list_id].to_i
    @card.position = params[:position].to_i
    @card.save

    head :ok
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:title)
    end
end

app/controllers/lists/cards_controller.rb
class Lists::CardsController < ApplicationController
  include Assignable
  before_action :authenticate_user!
  before_action :set_list_and_board

  def new
    card = Card.new
    render turbo_stream: turbo_stream.replace(dom_id(@list), partial: "cards/form", locals: { card: card, list: @list, board: @board })
  end

  def create
    @card = @list.cards.new(card_params)

    respond_to do |format|
      if @card.save
        add_creator(current_user_account, @card)
        card = Card.new
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(dom_id_for_records(@list, card), partial: "cards/new", locals: { card: card, list: @list })
        }
        format.html { redirect_to @board }
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(dom_id_for_records(@list, @card), partial: "cards/form", locals: { card: @card, list: @list })
        }
        format.html { redirect_to @board }
      end
    end
  end

  private

  def set_list_and_board
    @list = List.find(params[:list_id])
    @board = @list.board
  end

  def card_params
    params.require(:card).permit(:title)
  end
end

app/views/cards/_card.html.erb
<div id="<%= card.id %>"> 
<%= turbo_stream_from card %>
<%= turbo_frame_tag dom_id(card) do %>
  <div class="card">
    <div class="d-flex justify-content-between px-2">
      <%= card.title %>
      <div class="d-flex">
        <%= button_to "Edit", edit_card_path(card), method: :get, class: "btn btn-sm btn-outline-secondary" %>
        <%= button_to "Delete", card_path(card), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-sm btn-outline-secondary' %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/cards/_form.html.erb
<% model = [local_assigns[:list], card].compact %>
<%= turbo_frame_tag dom_id_for_records(*model) do %>
  <%= form_with model: model, local: true,
    id: dom_id_for_records(*model) do |form| %>

    <div class="card">
      <%= form.text_area :title %>
    </div>
    <%= form.submit class: "btn btn-primary btn-sm" %>
    <%= link_to "Cancel", card, class: "btn btn-link" if form.object.persisted? %>
    <%= link_to "Cancel", cancel_list_path(list), class: "btn btn-link" if !form.object.persisted? %>
  <% end %>
<% end %>

app/views/cards/_new.html.haml
= turbo_frame_tag list do
  = link_to "Add card", new_list_card_path(list), class: "btn no-border d-grid gap-2"

app/views/cards/edit.html.erb
<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<%= render @card %>