config/routes.rb
Rails.application.routes.draw do      
  root "application#hello"
  require "sidekiq/web"
  require "sidekiq/cron/web"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    registrations: "registrations",
    invitations: "admin/invitations"
  }

  namespace :admin do
    resources :users do 
      post '/archive', to: "users#archive"
    end
  end

  get "account/:id", to: "application#select_tenant", as: :select_tenant
  resources :boards, path: :canvasses
  resources :cards do 
    member do 
      patch :move
    end
  end
  resources :forms, path: :questions do 
    post '/pause', to: "forms#pause"
    resources :fields do 
      resources :field_values
    end
  end
  resources :lists do 
    member do 
      get :cancel
    end
    resources :cards, module: :lists
  end
  resources :templates
  resources :work_items, except: [:show, :destroy, :edit] do 
    patch "/cancel", to: "work_items#cancel"
  end
  get '/user_account', to: 'user_accounts#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :trackable
  has_person_name
  has_many :user_accounts
  has_many :accounts, through: :user_accounts
  has_many :user_roles
  has_many :roles, through: :user_roles
  accepts_nested_attributes_for :accounts
  validates :name, :email, presence: true
  validates :roles, presence: true
  before_create :has_roles
  
  def has_roles
    if user_roles.size == 0
      errors[:roles] << "can't be blank"
      throw(:abort)
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  include Assignable
  before_action :set_form, only: [:show, :pause, :edit, :update]
  before_action :set_forms, only: [:index]  

  def index
  end

  def new
    @time_of_day = Time.now.strftime("%H:%m")
    @form = Form.new
  end

  def show
    @field = @form.fields.first
    @field_value = @form.fields.first.field_values.build
    @grouped_by_day_field_values = @field.field_values.reverse.group_by { |field_value|
      field_value.created_at.strftime("%d %B %Y")
    }
  end

  def create
    @form = Form.new(description: form_params[:description])
    @recurrence = form_params[:schedule_recurrence]
    @time_of_day = Time.parse(form_params[:schedule_time_of_day])
    @user_account_ids = form_params[:allocation_ids].reject(&:blank?).map(&:to_i)

    if @form.valid? && @recurrence != 'null' && !@user_account_ids.empty?
      @form.save   
      @form.fields.create(name: 'question_answer', field_type: Field.field_types[:string])
      create_schedule(form_params)
      allocate_users(current_user_account, @form, @user_account_ids)
      add_creator(current_user_account, @form)

      respond_to do |format|
          format.html  { redirect_to(@form,
                        :notice => 'Question was successfully created.') }
      end
    else      
      @recurrence == 'null' ? @form.errors.add(:schedule_recurrence, "can't be blank") : nil
      @user_account_ids.empty? ? @form.errors.add(:allocations, "can't be blank") : @user_account_ids
      @current_tenant_user_accounts = current_tenant.user_accounts.map{|obj| [obj.user.name, obj.id] }
      @time_of_day = form_params[:schedule_time_of_day]

      render :new
    end
  end

  def edit
  end

  def update
    @user_account_ids = form_params[:allocation_ids].reject(&:blank?).map(&:to_i)
    if form_params[:description].present? && !@user_account_ids.empty?
      @form.update(description: form_params[:description])
      allocate_users(current_user_account, @form, @user_account_ids)

      respond_to do |format|
        format.html  { redirect_to(@form,
                      :notice => 'Question was successfully updated.') }
      end
    else
      form_params[:description].empty? ? @form.errors.add(:description, "can't be blank") : ""
      @user_account_ids.empty? ? @form.errors.add(:allocations, "can't be blank") : @user_account_ids
      @current_tenant_user_accounts = current_tenant.user_accounts.map{|obj| [obj.user.name, obj.id] }
      render :edit
    end
  end

  def allocate_users(actor, object, allocated_ids)
    deallocate_users(actor, object, allocated_ids)
  
    allocated_ids.each do |id|
      if !id.in? object.allocations.map(&:recipient_id) 
        object.allocations.create(
          actor_id: actor.id, 
          recipient_id: id, 
          action_object_type: object.class.name,
          action_object_id: object.id
        )
      end
    end
  end

  def deallocate_users(actor, object, allocated_ids)
    if object.allocations.present?
      object.allocations.each do |allocation|
        if !allocation.recipient_id.in? allocated_ids
          allocation.update(
            actor_id: actor.id,
            action_type: :deallocated)
        end
      end
    end
  end

  def create_schedule(form_params)
    recurrence = form_params[:schedule_recurrence]
    time_of_day = Time.parse(form_params[:schedule_time_of_day])
    @form.events.create(start_time: time_of_day, recurring: recurrence)
  end

  def pause
    @form.toggle!(:paused)
    redirect_to @form
  end

  private

  def set_form
    id = params[:id] || params[:form_id]
    @form = Form.find(id)
  end

  def set_forms
    @questions = Form.all
    @allocated_questions = current_user_account.allocated_forms
  end

  def form_params
    params.require(:form).permit(:description, :schedule_recurrence, 
      :schedule_time_of_day, allocation_ids: [])
  end
end

app/views/forms/_index_allocated_questions.html.haml
- if questions.present?
  - questions.each do |question|
    %table.table-sm.table-outline
      %tbody
        %tr
          %td
            - if question.paused
              = "This check-in is paused, nobody is being asked."
            - else
              = "Asking #{pluralize(question.allocations.count, 'person')}"
              = question.rule
              = " at " + question.time_of_day
            %h5= link_to question.description, form_path(question)

- else
  %table.table-sm.table-outline
    %tbody
      %tr
        %td
          %p No questions

app/views/forms/_index_questions.html.haml
- if questions.present?
  - questions.each do |question|
    %table.table-sm.table-outline
      %tbody
        %tr
          %td
            - if question.paused
              = "This check-in is paused, nobody is being asked."
            - else
              = "Asking #{pluralize(question.allocations.count, 'person')}"
              = question.rule
              = " at " + question.time_of_day
            %h5= link_to question.description, form_path(question)
- else
  %table.table-sm.table-outline
    %tbody
      %tr
        %td
          %p No questions

app/views/forms/edit.html.haml
.col-md-6
  %h3 Edit question
  = simple_form_for(@form) do |f|
    = render 'layouts/error_messages', object: f.object
    .mb-3
      = f.input :description, label: "What question do you want to ask?"
    .mb-3
      = f.association :allocations, input_html: { id: 'dropdown-choice-select', multiple: true }, selected: @form.allocated_user_account_ids, required: true, label: "Who do you want to ask?", collection: @current_tenant_user_accounts, label_method: :first, value_method: :second
    = f.button :submit, value: "Start collecting answers", class: "btn btn-sm btn-outline-secondary float-end"

app/views/forms/index.html.haml
= link_to "New recurring question", new_form_path, class: "btn btn-sm btn-outline-secondary float-end"
%nav.border-bottom
  #nav-tab.border-0.nav.nav-tabs{role: "tablist"}
    %button#nav-home-tab.nav-link.active{"aria-controls" => "nav-home", "aria-selected" => "true", "data-bs-target" => "#nav-home", "data-bs-toggle" => "tab", role: "tab", type: "button"} Assigned
    %button#nav-profile-tab.nav-link{"aria-controls" => "nav-profile", "aria-selected" => "false", "data-bs-target" => "#nav-profile", "data-bs-toggle" => "tab", role: "tab", type: "button"} All
#nav-tabContent.tab-content
  #nav-home.tab-pane.fade.show.active{"aria-labelledby" => "nav-home-tab", role: "tabpanel"}
    = render 'forms/index_allocated_questions', questions: @allocated_questions
  #nav-profile.tab-pane.fade{"aria-labelledby" => "nav-profile-tab", role: "tabpanel"}
    = render 'forms/index_questions', questions: @questions

app/views/forms/new.html.haml
.col-md-6
  %h3 New question
  = simple_form_for(@form) do |f|
    = render 'layouts/error_messages', object: f.object
    .mb-3
      = f.input :description, label: "What question do you want to ask?"
    .form-group.mb-3
      = f.label "How often do you want to ask?", for: :schedule_recurrence, required: true
      %br
      = f.select_recurring :schedule_recurrence
      = f.full_error :schedule_recurrence, class: "invalid-feedback"
    .mb-3  
      = f.input :schedule_time_of_day, label: "At what time of the day?", as: :string, input_html: {type: "time", value: @time_of_day }, required: true
    .mb-3
      = f.association :allocations, input_html: { id: 'dropdown-choice-select' }, selected: @user_account_ids, required: true, label: "Who do you want to ask?", collection: @current_tenant_user_accounts, label_method: :first, value_method: :second
    = f.button :submit, value: "Start collecting answers", class: "btn btn-sm btn-outline-secondary float-end"
  = button_to "Cancel", :back, method: :get

app/views/forms/show.html.haml
- if @form.paused
  = "This check-in is paused, nobody is being asked."
- else 
  = "Asking #{pluralize(@form.allocations.count, 'person')}"
  = @form.rule
  = " at " + @form.time_of_day
.float-end.dropdown
  %a#dropdownMenuButton.btn.btn-sm.btn-outline-secondary{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :type => "button"}
    = raw('&#9998;')
  #dropdown-recurring-form.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
    = link_to "Edit", edit_form_path(@form), class: "dropdown-item"
    - if @form.paused
      = link_to "Start asking", form_pause_path(@form), class: "dropdown-item", method: :post
    - else 
      = link_to "Pause asking", form_pause_path(@form), class: "dropdown-item", method: :post
%h4= @form.description
- if !@form.paused
  = render 'field_values/new', form: @form, field: @field, field_value: @field_value
= render 'field_values/index', grouped_by_day_field_values: @grouped_by_day_field_values