config/routes.rb
Rails.application.routes.draw do      
  root "application#hello"
  require "sidekiq/web"
  require "sidekiq/cron/web"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    registrations: "registrations",
    invitations: "admin/invitations"
  }

  namespace :admin do
    resources :users do 
      post '/archive', to: "users#archive"
    end
  end

  get "account/:id", to: "application#select_tenant", as: :select_tenant
  resources :boards, path: :canvasses
  resources :cards do 
    member do 
      patch :move
    end
  end
  resources :forms, path: :questions do 
    post '/pause', to: "forms#pause"
    resources :fields do 
      resources :field_values
    end
  end
  resources :lists do 
    member do 
      get :cancel
    end
    resources :cards, module: :lists
  end
  resources :templates
  resources :work_items, except: [:show, :destroy, :edit] do 
    patch "/cancel", to: "work_items#cancel"
  end
  get '/user_account', to: 'user_accounts#show'
end

app/views/layouts/_error_messages.html.haml
- if object.errors.any?
  #error_explanation.alert.alert-danger
    The form contains #{pluralize(object.errors.count, "error")}:
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          #{msg}

app/views/layouts/_navigation_breadcrumbs.html.haml
- if current_user.present?
  .d-block.d-sm-none.border-bottom
    = render "layouts/navigation_left_dropdown"

app/views/layouts/_navigation_left.html.haml
- if current_user.present?
  %nav.col-sm-2.col-md-2.col-lg-2.bg-light.sidebar.d-none.d-sm-block
    .sidebar-sticky.pt-3
      %ul.nav.flex-column
        %li.nav-item
          = link_to "Canvasses", boards_path, class: "nav-link"
          = link_to "Templates", templates_path, class: "nav-link"
          = link_to "Work Items", work_items_path, class: "nav-link"
          = link_to "Questions", forms_path, class: "nav-link"
          = link_to "Users", admin_users_path, class: "nav-link"
          = link_to "Profile", user_account_path, class: "nav-link"

app/views/layouts/_navigation_left_dropdown.html.haml
.dropdown
  %a#navbarDropdownMenuLinkLeft.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
    %svg{height: "20", viewbox: "0 0 100 100", width: "20"}
      %rect{height: "10", width: "100"}
      %rect{height: "10", width: "100", y: "30"}
      %rect{height: "10", width: "100", y: "60"}
  .dropdown-menu.dropdown-menu-nav-left{"aria-labelledby" => "navbarDropdownMenuLinkLeft"}
    .d-flex
      %a.p-2.btn.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "dropdown"}
    = link_to "Canvasses", boards_path, class: "nav-link"
    = link_to "Templates", templates_path, class: "nav-link"
    = link_to "Work Items", work_items_path, class: "nav-link"
    = link_to "Questions", forms_path, class: "nav-link"
    = link_to "Users", admin_users_path, class: "nav-link"
    = link_to "Profile", user_account_path, class: "nav-link"

app/views/layouts/_navigation_top_board.html.haml
%header.navbar.navbar-expand.navbar-light.sticky-top.flex-md-nowrap.p-0.bg-light
  = render "layouts/navigation_top_left"
  = render "layouts/navigation_left_dropdown"
  = render "layouts/navigation_top_right"

app/views/layouts/_navigation_top_default.html.haml
%header.navbar.navbar-expand.navbar-light.sticky-top.flex-md-nowrap.p-0.bg-light
  = render "layouts/navigation_top_left"
  = render "layouts/navigation_top_right"

app/views/layouts/_navigation_top_left.html.haml
= link_to "Home", root_path, class: "navbar-brand-custom px-3"

app/views/layouts/_navigation_top_right.html.haml
.navbar-nav.ms-auto
  - if user_signed_in?
    .dropdown
      %a#navbarDropdownMenuLink.dropdown-toggle.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
        = current_user.name
      .dropdown-menu.dropdown-menu-accounts{"aria-labelledby" => "navbarDropdownMenuLink"}
        .nav-link
          - @accounts.each do |account|
            = link_to account.name, select_tenant_path(account.id), class: "nav-link #{account.id == session[:current_tenant_id].to_i ? 'active border border-secondary rounded' : ''}"
        .dropdown-divider
        .nav-link
          = link_to "Logout", destroy_user_session_path, method: "delete", class: "nav-link"
  - else
    = link_to "Sign up", new_user_registration_path, class: "nav-link"
    = link_to "Login", new_user_session_path, class: "nav-link"
    - if !Rails.env.production? 
      = link_to "Login directly", user_session_path("user" => { "email" => "0@0.com", "password" => "123123" }), class: "nav-link", method: :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    = stylesheet_pack_tag "stylesheet", media: "all", "data-turbolinks-track": "reload"
    = csrf_meta_tags
  %body
    = render "layouts/navigation_top_default"
    = render "layouts/navigation_breadcrumbs"
    .container-fluid
      .row
        = render "layouts/navigation_left"
        %main.col-sm-10.d-md-block.ms-sm-auto.px-md-4.mt-1
          .row 
            .col-md-9
              - if notice
                %p.alert.alert-success= notice
              - if alert
                %p.alert.alert-danger= alert
              = yield

app/views/layouts/board.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    = stylesheet_pack_tag "stylesheet", media: "all", "data-turbolinks-track": "reload"
    = csrf_meta_tags
  %body
    = render "layouts/navigation_top_board"
    .container-fluid
      .row
        .col-12
          - if notice
            %p.alert.alert-success= notice
          - if alert
            %p.alert.alert-danger= alert
          = yield

app/views/layouts/hello.html.erb
<h1><%= current_user ? "Welcome" : "Hello" %></h1>